config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	resources :users, only: [:index, :destroy]

	resources :projects do
		get :search, on: :collection
	end

	resources :comments
	
	root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord

	include ActionView::Helpers::DateHelper

    TYPES = ['Public','Private']
    STATUSES = ['Created', 'Started', 'Stopped', 'Completed']

	belongs_to :user
	has_many :comments, dependent: :destroy

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, length: { in: 20..200 }
	validates :project_type, inclusion: { in: TYPES, message: "%{value} is not a valid type" }
  	validates :project_status, inclusion: { in: STATUSES, message: "%{value} is not a valid status" }
    validates :estimated, inclusion: { in: 1..10 }
    validates :actual, inclusion: { in: 1..10 }

    attribute :created_time_ago
    attribute :project_owner

    def created_time_ago
    	time_ago_in_words(self.created_at)
    end

    def project_owner
        return self.user.name
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

 has_many :projects
 has_many :comments

 validates :name, presence: true
 
def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.project = Project.find(comment_params[:project_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.project, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    authorize @comment
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    authorize @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :body, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = policy_scope(Project)
    # render json: policy_scope(Project)
    # render json: Project.all
  end

  def search
    query = params[:query]
    projects = Project.where('name LIKE ? OR description LIKE ?',
                         "%#{query}%", "%#{query}%")
    render json: projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    authorize @project
    @comments = @project.comments.all
    @comment = @project.comments.build
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize @project
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize @project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :project_type, :estimated, :actual, :project_status, :user_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
     authorize @users
  end

 def destroy
 	@user = User.find(params[:id])
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_params
      params.require(:project).permit(:name, :description, :project_type, :estimated, :actual, :project_status, :user_id)
    end
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
    <%= form.hidden_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Lexop</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application' %>
	<%= javascript_include_tag 'application' %>


</head>

<body>
	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a href="#" class="navbar-brand">Home Improvement</a> </div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
					<%= link_to("New Project", new_project_path, class: 'btn btn-default navbar-btn') %>
					<%= link_to("View Projects", projects_path, class: 'btn btn-default navbar-btn') %>
					<% unless current_user %> 
						<%= link_to("Sign in with Facebook", user_facebook_omniauth_authorize_path, class: 'btn btn-default navbar-btn navbar-right') %>
						<%= link_to('Login', new_user_session_path, class: 'btn btn-default navbar-btn navbar-right')  %>
						<%= link_to('Register', new_user_registration_path, class: 'btn btn-default navbar-btn navbar-right')  %>
					<% else %>
					<% if current_user.admin? %>
					    <%= link_to("View Users", users_path, class: 'btn btn-default navbar-btn') %>
					<% end %>
						<span class="text-success">Logged In As: <%= current_user[:name] %></span>
						<%= link_to("Logout", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn navbar-right') %>
					<% end %>
				
				</div>
			</div>
		</nav>
		

		<div class="container wrapper">
		<% if notice %>
			<div class="alert alert-warning"><%= notice %></div>
			<% end %>
			<% if alert %>
			<div class="alert alert-danger"><%= alert %></div>
		<% end %>
			<%= yield %>
		</div>
	</body>
	</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :project_type %>
    <%= form.select(:project_type, Project::TYPES, {}, {id: 'project_type'}) %>
  </div>

  <div class="field">
    <%= form.label :estimated %>
    <%= form.number_field :estimated, in: 1...11, id: :project_estimated %>
  </div>

  <div class="field">
    <%= form.label :actual %>
    <%= form.number_field :actual, in: 1...11, id: :project_actual %>
  </div>

  <div class="field">
    <%= form.label :project_status %>
    <%= form.select(:project_status, Project::STATUSES, {}, {id: 'project_status'}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= react_component("ProjectApplication", {projects: @projects}) %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @project.project_type %>
</p>

<p>
  <strong>Estimated:</strong>
  <%= @project.estimated %>
</p>

<p>
  <strong>Actual:</strong>
  <%= @project.actual %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.project_status %>
</p>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_id %></strong>
    <br>
    <p><%= comment.body %></p>
  
  </div>
  <% if policy(comment).update? %>
     <p><%= link_to 'Edit', edit_comment_path(comment) %></p>
  <% end %>
  <% if policy(comment).destroy? %>
     <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment, project_id: @project.id } %>

<% if policy(@project).update? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="container">
    <div class="panel panel-primary">
      <div class="panel-heading">
      <%= user.name %>
      <%= link_to 'Delete', 
      					user_path(user), 
                         method: :delete, 
                         class: 'btn btn-warning',
                         data: { confirm: 'Are you sure you want to delete this user?' } %> </div>
      <div class="panel-body">
        <ul>
          <li>Email: <%= user.email %></li>
          <li>User ID: <%= user.id %></li>
          <li>Is Administrator: <%= user.admin %></li>
          <li>Last Signed In: <%= user.last_sign_in_at.strftime('%H:%M:%S %B, %d, %Y') %></li>
        </ul>
      </div>
      <div class="panel-footer"></div>
    </div>
  </div>
<% end %>